name: CI

on:
  push:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node v14.15.0
      uses: actions/setup-node@v2
      with:
        node-version: 14.15.0
    - name: Install dependencies
      run: npm install
    - name: ESLint
      run: npm run lint
